[package]
name = "plain-rss"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html2text = "0.2"
opml = "1.1"
reqwest = { version = "0.11", features = ["blocking"] }
feed-rs = "1.0"
sqlite = "0.26"
